"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { readAuthUser } from "@/components/auth-store";

type DealerData = { profile: { business_name: string; commission_rate: number; status: string; area: string } | null; orders: Array<{ id: string; order_number: string; status: string; total_vnd: number; dealer_commission_vnd: number; dealer_commission_status: string; created_at: string }>; summary: { order_count: number; commission_pending_vnd: number; commission_approved_vnd: number; commission_paid_vnd: number } };
const money = (value: number) => new Intl.NumberFormat("vi-VN").format(value) + "đ";
const statusLabels: Record<string, string> = { pending: "Chờ xác nhận", confirmed: "Đã xác nhận", packing: "Đang chuẩn bị", shipping: "Đang giao", delivered: "Đã giao", cancelled: "Đã hủy" };
const commissionLabels: Record<string, string> = { pending: "Chờ duyệt", approved: "Đã duyệt", paid: "Đã thanh toán", cancelled: "Đã hủy" };

export default function DealerPage() {
  const [data, setData] = useState<DealerData | null>(null);
  const [message, setMessage] = useState("Đang tải dữ liệu đại lý...");
  useEffect(() => {
    if (!readAuthUser()) { setMessage("Vui lòng đăng nhập bằng tài khoản đại lý để tiếp tục."); return; }
    fetch("/api/v1/dealer/overview", { cache: "no-store" }).then((response) => response.json().then((payload) => ({ response, payload }))).then(({ response, payload }) => { if (!response.ok || !payload.ok) throw new Error(payload?.error?.message || "Không thể tải dữ liệu đại lý."); setData(payload.data); setMessage(""); }).catch((error) => setMessage(error instanceof Error ? error.message : "Không thể tải dữ liệu đại lý."));
  }, []);
  if (!data) return <main className="section pt-12"><div className="container"><div className="card rounded-[28px] p-8 text-center text-[var(--muted)]">{message}</div></div></main>;
  return <main className="section pt-8 pb-24 md:pt-14"><div className="container space-y-6"><div className="rounded-[32px] bg-[linear-gradient(135deg,#0f4d32,#247447)] p-6 text-white shadow-[0_18px_38px_rgba(15,77,50,0.18)] md:p-9"><div className="text-xs font-semibold uppercase tracking-[0.2em] text-white/70">Khu vực đại lý</div><h1 className="mt-3 text-4xl font-semibold tracking-[-0.05em] md:text-6xl">{data.profile?.business_name || "Đối tác Hòa Phúc"}</h1><p className="mt-3 text-sm text-white/75">{data.profile?.area || "Chưa cập nhật khu vực"} · Chính sách hoa hồng {data.profile?.commission_rate ?? 0}% · {data.profile?.status === "active" ? "Đang hoạt động" : "Chờ kích hoạt"}</p></div><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Đơn hợp lệ", data.summary.order_count], ["Chờ duyệt", money(data.summary.commission_pending_vnd)], ["Đã duyệt", money(data.summary.commission_approved_vnd)], ["Đã thanh toán", money(data.summary.commission_paid_vnd)]].map(([label, value]) => <article key={String(label)} className="card rounded-[24px] p-5"><div className="text-xs uppercase tracking-[0.14em] text-[var(--muted)]">{label}</div><div className="mt-3 text-2xl font-semibold text-[var(--green-dark)]">{value}</div></article>)}</section><section className="card rounded-[28px] p-5 md:p-7"><div className="flex items-center justify-between gap-4"><div><div className="eyebrow text-[11px]">Đối soát</div><h2 className="mt-2 text-2xl font-semibold text-[var(--green-dark)]">Đơn hàng và hoa hồng</h2></div><Link href="/san-pham" className="button button-secondary px-3 py-2 text-xs">Xem sản phẩm</Link></div><div className="mt-5 space-y-3">{data.orders.length ? data.orders.map((order) => <div key={order.id} className="flex flex-wrap items-center justify-between gap-3 rounded-[20px] border border-[rgba(15,77,50,0.1)] p-4"><div><div className="font-semibold text-[var(--green-dark)]">{order.order_number}</div><div className="mt-1 text-xs text-[var(--muted)]">{new Date(order.created_at).toLocaleDateString("vi-VN")} · {statusLabels[order.status] || order.status}</div></div><div className="text-right"><div className="font-semibold text-[var(--green)]">{money(order.dealer_commission_vnd)}</div><div className="mt-1 text-xs text-[var(--muted)]">{commissionLabels[order.dealer_commission_status] || order.dealer_commission_status} · Đơn {money(order.total_vnd)}</div></div></div>) : <p className="rounded-2xl bg-[rgba(15,77,50,0.05)] p-5 text-sm text-[var(--muted)]">Chưa có đơn hàng được ghi nhận cho đại lý.</p>}</div></section></div></main>;
}
